### ISSUE TITLE
nacos 1.2.0如何开启认证   

### ISSUE THREAD

**Issue by jtl0813** [nacos-group/nacos-k8s#108]
只能通过配置文件的方式吗  nacos.core.auth.enabled=true
k8s下只能挂载configmap？还有别的办法吗

**Comment by paderlol** [comment]
只能通过环境变量的方式去做这个，不过可以动态更改，因为nacos会实时读取，具体环境变量名，看nacos docker 的readme，有说明

**Comment by jtl0813** [comment]
ok 多谢

**Comment by jtl0813** [comment]
nacos1.2.0更改密码报错

java.lang.NullPointerException: null
	at com.alibaba.nacos.console.controller.UserController.updatePassword(UserController.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:663)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)

**Comment by paderlol** [comment]
这个右上角更改密码确实有问题，你可以提到nacos去，使用列表菜单里面的更改密码吧

**Comment by jtl0813** [comment]
好的  多谢  及时响应  点赞
