### ISSUE TITLE
nacos keeps starting after deploy on k8s

### ISSUE THREAD

**Issue by kaybinwong** [nacos-group/nacos-k8s#11]
**nacos deployment**
```
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.master.db.name: "nacos_devtest"
  mysql.master.port: "3306"
  mysql.slave.port: "3306"
  mysql.master.user: "nacos"
  mysql.master.password: "nacos"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 2
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nfs-client-provisioner
      initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plguindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_MASTER_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.db.name
            - name: MYSQL_MASTER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.port
            - name: MYSQL_SLAVE_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.slave.port
            - name: MYSQL_MASTER_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.user
            - name: MYSQL_MASTER_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
          readinessProbe:
            httpGet:
              port: client-port
              path: /nacos/v1/console/health/readiness
            initialDelaySeconds: 600
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: client-port
              path: /nacos/v1/console/health/liveness
            initialDelaySeconds: 600
            timeoutSeconds: 3
          volumeMounts:
            - name: plguindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: plguindir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: datadir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: logdir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
```

**checking the nacos's po**
```
[root@t-inf-dev02 nacos]# kubectl get po -l app=nacos -o wide
NAME      READY     STATUS    RESTARTS   AGE       IP              NODE
nacos-0   0/1       Running   4          53m       10.233.84.174   t-inf-dev01
```
nacos keeps starting, but never started.

**nacos's logs**

```
[root@nacos-0 logs]# tail -f nacos.log
.....
2019-02-14 11:07:56,720 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$23ff4ee7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-02-14 11:07:57,054 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-02-14 11:07:57,062 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@38f57b3d' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-02-14 11:07:57,074 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$48d3f199] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-02-14 11:07:57,088 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-02-14 11:07:57,682 INFO Nacos is starting...

2019-02-14 11:07:58,260 INFO Tomcat initialized with port(s): 8848 (http)

2019-02-14 11:07:58,330 INFO Initializing ProtocolHandler ["http-nio-8848"]

2019-02-14 11:07:58,370 INFO Starting service [Tomcat]

2019-02-14 11:07:58,370 INFO Starting Servlet Engine: Apache Tomcat/9.0.13

2019-02-14 11:07:58,406 INFO The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]

2019-02-14 11:07:58,627 INFO Initializing Spring embedded WebApplicationContext

2019-02-14 11:07:58,628 INFO Root WebApplicationContext: initialization completed in 7816 ms

2019-02-14 11:07:58,682 INFO Nacos is starting...

2019-02-14 11:07:59,684 INFO Nacos is starting...

2019-02-14 11:08:00,691 INFO Nacos is starting...

```

any idea? @paderlol

**Comment by wangyanzu** [comment]
我也遇到了，应该是节点只启动了一个造成的。

**Comment by wangyanzu** [comment]
一样的问题，发现 config.conf 没有内容
2019-02-22 17:18:55,552 INFO The server IP list of Nacos is []

**Comment by paderlol** [comment]
启动完成需要一段时间 因为自动发现设置了延时 包括健康检查

**Comment by kaybinwong** [comment]
@paderlol 一直启动不了，试了好几次。另外请问下一版本发布大概那时候？

**Comment by paderlol** [comment]
一直启动不了？可以通过describe看下是哪里的问题，nfs有没有安装？

**Comment by paderlol** [comment]
``` 
kubeclt describe pod nacos-0

```

**Comment by paderlol** [comment]
通过这个命令看下启动过程中发生了什么问题？

**Comment by paderlol** [comment]
我排查到问题了,是我这边的docker image脚本有问题,马上发布一个hotfix

**Comment by paderlol** [comment]
我已经修复了 你可以重新pull 一下nacos-server的docker image就好了,具体原因:https://github.com/nacos-group/nacos-docker/issues/19

**Comment by kinserlin** [comment]
我也是这个问题：重新pull了最新的镜像也不行
`Events:
  Type     Reason     Age                  From                    Message
  ----     ------     ----                 ----                    -------
  Normal   Scheduled  2m15s                default-scheduler       Successfully assigned default/nacos-0 to 192.168.1.132
  Normal   Pulling    2m14s                kubelet, 192.168.1.132  pulling image "nacos/nacos-peer-finder-plugin:latest"
  Normal   Pulled     2m12s                kubelet, 192.168.1.132  Successfully pulled image "nacos/nacos-peer-finder-plugin:latest"
  Normal   Created    2m12s                kubelet, 192.168.1.132  Created container
  Normal   Started    2m12s                kubelet, 192.168.1.132  Started container
  Warning  Unhealthy  47s (x3 over 67s)    kubelet, 192.168.1.132  Liveness probe failed: Get http://172.20.2.9:8848/nacos/v1/console/health/liveness: dial tcp 172.20.2.9:8848: connect: connection refused
  Warning  Unhealthy  21s (x5 over 61s)    kubelet, 192.168.1.132  Readiness probe failed: Get http://172.20.2.9:8848/nacos/v1/console/health/readiness: dial tcp 172.20.2.9:8848: connect: connection refused
  Normal   Pulling    17s (x2 over 2m11s)  kubelet, 192.168.1.132  pulling image "nacos/nacos-server:latest"
  Normal   Killing    17s                  kubelet, 192.168.1.132  Killing container with id docker://nacos:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Pulled     16s (x2 over 2m10s)  kubelet, 192.168.1.132  Successfully pulled image "nacos/nacos-server:latest"
  Normal   Created    16s (x2 over 2m10s)  kubelet, 192.168.1.132  Created container
  Normal   Started    16s (x2 over 2m10s)  kubelet, 192.168.1.132  Started container
[root@arch-k8s-master nacos]# `

**Comment by paderlol** [comment]
请把配置文件中的两个健康检查先关闭，因为0.8新增了登录，Url拦截没有把这两个检查忽略，所以导致这个问题Url，0.9.0会就没这个问题了。

**Comment by kinserlin** [comment]
已经去掉健康检查了，看日志依然是starting...
```[root@arch-k8s-master nacos]# kubectl describe pod nacos-0 -n default 
Name:           nacos-0
Namespace:      default
Node:           192.168.1.132/192.168.1.132
Start Time:     Fri, 01 Mar 2019 10:14:36 +0800
Labels:         app=nacos
                controller-revision-hash=nacos-5ffdf8d4bd
                statefulset.kubernetes.io/pod-name=nacos-0
Annotations:    pod.alpha.kubernetes.io/initialized: true
Status:         Running
IP:             172.20.2.11
Controlled By:  StatefulSet/nacos
Init Containers:
  peer-finder-plugin-install:
    Container ID:   docker://c5136d1f8a8751f3e101ec7c0ca9ec4cd8a533b4e0104965419ac1afa5295ba0
    Image:          nacos/nacos-peer-finder-plugin:latest
    Image ID:       docker-pullable://nacos/nacos-peer-finder-plugin@sha256:dc8775e5a3b9fa54c3cdeb43ecf32b32c3095526b55a6b56db0d78701ae9c9b7
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 01 Mar 2019 10:14:38 +0800
      Finished:     Fri, 01 Mar 2019 10:14:38 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /home/nacos/plugins/peer-finder from plguindir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nfs-client-provisioner-token-88dp9 (ro)
Containers:
  nacos:
    Container ID:   docker://256052af8a50e0eb158e58a65b7ea1105b21b04a6b5865efd7caa597cdd6de4a
    Image:          nacos/nacos-server:latest
    Image ID:       docker-pullable://nacos/nacos-server@sha256:31589ae4becd925fa3f38f214707761d8784659453d46a35c97dbfddbeb6b202
    Port:           8848/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 01 Mar 2019 10:14:40 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     500m
      memory:  2Gi
    Environment:
      NACOS_REPLICAS:                 3
      SERVICE_NAME:                   nacos-headless
      POD_NAMESPACE:                  default (v1:metadata.namespace)
      MYSQL_MASTER_SERVICE_DB_NAME:   <set to the key 'mysql.master.db.name' of config map 'nacos-cm'>   Optional: false
      MYSQL_MASTER_SERVICE_PORT:      <set to the key 'mysql.master.port' of config map 'nacos-cm'>      Optional: false
      MYSQL_SLAVE_SERVICE_PORT:       <set to the key 'mysql.slave.port' of config map 'nacos-cm'>       Optional: false
      MYSQL_MASTER_SERVICE_USER:      <set to the key 'mysql.master.user' of config map 'nacos-cm'>      Optional: false
      MYSQL_MASTER_SERVICE_PASSWORD:  <set to the key 'mysql.master.password' of config map 'nacos-cm'>  Optional: false
      NACOS_SERVER_PORT:              8848
      PREFER_HOST_MODE:               hostname
    Mounts:
      /home/nacos/data from datadir (rw)
      /home/nacos/logs from logdir (rw)
      /home/nacos/plugins/peer-finder from plguindir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nfs-client-provisioner-token-88dp9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  plguindir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  plguindir-nacos-0
    ReadOnly:   false
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-nacos-0
    ReadOnly:   false
  logdir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  logdir-nacos-0
    ReadOnly:   false
  nfs-client-provisioner-token-88dp9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nfs-client-provisioner-token-88dp9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type    Reason     Age   From                    Message
  ----    ------     ----  ----                    -------
  Normal  Scheduled  62s   default-scheduler       Successfully assigned default/nacos-0 to 192.168.1.132
  Normal  Pulling    61s   kubelet, 192.168.1.132  pulling image "nacos/nacos-peer-finder-plugin:latest"
  Normal  Pulled     60s   kubelet, 192.168.1.132  Successfully pulled image "nacos/nacos-peer-finder-plugin:latest"
  Normal  Created    60s   kubelet, 192.168.1.132  Created container
  Normal  Started    60s   kubelet, 192.168.1.132  Started container
  Normal  Pulling    59s   kubelet, 192.168.1.132  pulling image "nacos/nacos-server:latest"
  Normal  Pulled     58s   kubelet, 192.168.1.132  Successfully pulled image "nacos/nacos-server:latest"
  Normal  Created    58s   kubelet, 192.168.1.132  Created container
  Normal  Started    58s   kubelet, 192.168.1.132  Started container  
```  
```2019-03-01 10:17:33,211 INFO Nacos is starting...

2019-03-01 10:17:53,517 INFO The server IP list of Nacos is []

2019-03-01 10:17:53,548 INFO Starting Nacos v0.8.0 on nacos-1.nacos-headless.default.svc.cluster.local. with PID 19 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)

2019-03-01 10:17:53,550 INFO No active profile set, falling back to default profiles: default

2019-03-01 10:17:54,531 INFO Nacos is starting...

2019-03-01 10:17:55,561 INFO Nacos is starting...

2019-03-01 10:17:56,583 INFO Nacos is starting...

2019-03-01 10:17:57,176 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpr
ingCGLIB$$4917ba27] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-03-01 10:17:57,356 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not
 eligible for auto-proxying)

2019-03-01 10:17:57,363 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@2e54db99' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not
 eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-03-01 10:17:57,373 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguratio
n$$EnhancerBySpringCGLIB$$6dec5cd9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-03-01 10:17:57,385 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible
 for auto-proxying)

2019-03-01 10:17:57,587 INFO Nacos is starting...

2019-03-01 10:17:58,102 INFO Tomcat initialized with port(s): 8848 (http)

2019-03-01 10:17:58,130 INFO Initializing ProtocolHandler ["http-nio-8848"]

2019-03-01 10:17:58,172 INFO Starting service [Tomcat]

2019-03-01 10:17:58,172 INFO Starting Servlet Engine: Apache Tomcat/9.0.13

2019-03-01 10:17:58,199 INFO The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]

2019-03-01 10:17:58,358 INFO Initializing Spring embedded WebApplicationContext

2019-03-01 10:17:58,358 INFO Root WebApplicationContext: initialization completed in 4702 ms

2019-03-01 10:17:58,593 INFO Nacos is starting...

2019-03-01 10:17:59,595 INFO Nacos is starting...

2019-03-01 10:18:00,598 INFO Nacos is starting...

2019-03-01 10:18:01,601 INFO Nacos is starting...

2019-03-01 10:18:02,604 INFO Nacos is starting...

2019-03-01 10:18:03,607 INFO Nacos is starting...

2019-03-01 10:18:04,611 INFO Nacos is starting...

2019-03-01 10:18:05,613 INFO Nacos is starting...

2019-03-01 10:18:06,613 INFO Nacos is starting...

**Comment by paderlol** [comment]
嗯，我看了你的日志，应该是docker镜像还是没更新导致的，之前我修复了这个脚本问题。你可以用docker pull重新手动拉取一下看看

**Comment by kinserlin** [comment]
启动后，这是个bug？
```java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.default.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848]
        at com.alibaba.nacos.naming.raft.PeerSet.local(PeerSet.java:191)
        at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectmetrics(PerformanceLoggerThread.java:114)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)```  

解析出来的地址，多了一个 “."  nacos-0.nacos-headless.default.svc.cluster.local.:8848

**Comment by paderlol** [comment]
你使用的k8s版本是?

**Comment by kinserlin** [comment]
v1.12.4

**Comment by paderlol** [comment]
我这边用的也是1.12 没有这个点的问题

**Comment by paderlol** [comment]
你尝试使用下1.12.2这个版本看看,k8s版本间有时候会出现一些不兼容的问题
