### ISSUE TITLE
通过helm chart 部署，如何用一个外部MySQL数据库？

### ISSUE THREAD

**Issue by wwyhy** [nacos-group/nacos-k8s#110]
Hi，

通过helm chart 部署，如何用一个外部MySQL数据库？
只看到到了数据库的用户名，密码，DB， 但是没有看到DB主机的定义呢？

谢谢！

**Comment by paderlol** [comment]
重新更新下工程,我增加了一个dbHost的属性,但是理论上来讲,你们既然使用kubernetes,那么引入外部数据库应该也要应该通过service endpoint的方式去引用的.不然每次更换数据库连接都要重新配置helm

**Comment by wwyhy** [comment]
你好， 感谢你的及时支持。

主要是因为，如果是生产环境的话，容器化的MySQL还不太敢用。我们会通过自定义value来覆盖默认value。

最后， 我看了下你的更新， 有点不明白， 这里的not是不是写错了？

{{- if **not** .Values.env.dbHost  }}
- name: MYSQL_SERVICE_HOST
value: {{ .Values.env.dbHost | quote }}
{{- end }}


谢谢！

**Comment by paderlol** [comment]
谢谢指正,已经修改了, 我说的不是让你们使用容器来做数据库,而是利用kubernetes的service去代理你们的外部数据库地址,可以统一管理,以后替换地址就只需要更新service就可以了

**Comment by wwyhy** [comment]
嗯， 明白你的意思了，谢谢！

**Comment by wwyhy** [comment]
配置了外部数据库后， 启动报错：
replicaCount: 3， mode: cluster, helm部署
已验证， 数据库没问题并且pod可以正常访问数据库， 
```
2020-03-26 18:32:34,096 INFO Reflections took 4 ms to scan 1 urls, producing 3 keys and 15 values

2020-03-26 18:32:34,574 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.2.0.jar!/com/alibaba/nacos/config/server/controller/OpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

2020-03-26 18:32:34,579 INFO Stopping service [Tomcat]

2020-03-26 18:32:34,582 WARN The web application [nacos] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)

```

**Comment by paderlol** [comment]
你数据库用的什么版本？

**Comment by paderlol** [comment]
nacos K8s不支持 MySQL 8

**Comment by wwyhy** [comment]
用的是MySQL 5.7. 我看start.out 的日志是没有表， 如果用外部数据库的话，是需要手动导入init SQL脚本吗？

```
2020-03-26 20:56:13,678 INFO Nacos data files: /home/nacos/data/

2020-03-26 20:56:13,678 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.

org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [DELETE FROM config_info WHERE data_id='com.alibaba.nacos.testMasterDB']; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nacos.config_info' doesn't exist
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:234)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
        at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl$SelectMasterTask.run(BasicDataSourceServiceImpl.java:317)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nacos.config_info' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

**Comment by paderlol** [comment]
是的，需要自己导入表和数据

**Comment by wwyhy** [comment]
我用容器里的/home/nacos/conf/schema.sql脚本导入，  报了很多语法错。

```
root@localhost 21:17:  [nacos]>source ./nacos.sql
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AUTHORIZATION nacos' at line 1
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id va' at line 2
ERROR 1146 (42S02): Table 'nacos.config_info' doesn't exist
ERROR 1146 (42S02): Table 'nacos.config_info' doesn't exist
ERROR 1146 (42S02): Table 'nacos.config_info' doesn't exist
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id va' at line 3
ERROR 1146 (42S02): Table 'nacos.his_config_info' doesn't exist
ERROR 1146 (42S02): Table 'nacos.his_config_info' doesn't exist
ERROR 1146 (42S02): Table 'nacos.his_config_info' doesn't exist
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id va' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id va' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id va' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
 app_name varchar(128) NOT NULL,
 is_dynamic_c' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  app_name varchar(128) NOT NULL,
  data_id va' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  app_name varchar(128) NOT NULL,
  data_id va' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  constraint config_tags_id_key PRIMARY KEY (n' at line 8
ERROR 1146 (42S02): Table 'nacos.config_tags_relation' doesn't exist
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  group_id varchar(128) DEFAULT '',
  quota in' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  tenant_id varchar(128) DEFAULT '',
  quota i' at line 2
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'generated by default as identity,
  kp varchar(128) NOT NULL,
  tenant_id varcha' at line 2
ERROR 1146 (42S02): Table 'nacos.tenant_info' doesn't exist
ERROR 1050 (42S01): Table 'users' already exists
ERROR 1050 (42S01): Table 'roles' already exists
ERROR 1050 (42S01): Table 'permissions' already exists
ERROR 1062 (23000): Duplicate entry 'nacos' for key 'PRIMARY'
ERROR 1062 (23000): Duplicate entry 'nacos-ROLE_ADMIN' for key 'uk_username_role'
```

**Comment by paderlol** [comment]
不要用schme  用另外一个脚本 schme是给derby用的

**Comment by wwyhy** [comment]
请问下， 哪里可以找到这个init SQL， 谢谢！

**Comment by paderlol** [comment]
你下载nacos的 release包就在conf里面就可以看到

**Comment by wwyhy** [comment]
感谢， 已导入SQL， 集群正常运行了。

**Comment by paderlol** [comment]
客气,如果处理完,那麻烦关闭一下issue哈
