### ISSUE TITLE
能提供ceph部署的例子吗

### ISSUE THREAD

**Issue by mawennan** [nacos-group/nacos-k8s#12]
能提供ceph部署的例子吗 谢谢

**Comment by paderlol** [comment]
好的，我最近会考虑做一版的

**Comment by mawennan** [comment]
nice!!   ：）

**Comment by mawennan** [comment]
GA了 ceph部署啥时候能到来

**Comment by paderlol** [comment]
实在不好意思，之前说会做的，因为很多事情耽搁了，我最近找时间做一下，如果你已经有相关的方案了，也可以提交PR贡献下。😂

**Comment by mawennan** [comment]
Hi 我本地配置了ceph，mysql和项目都可以正常启动，mysql挂载ceph-rbd，nacos挂载cephfs，但是创建服务的时候提示报错，我怎么进一步定位问题。。

![nacos-error](https://user-images.githubusercontent.com/4082983/56188998-77d03380-6059-11e9-9d34-6f1e8aa4734c.png)

![nacos2](https://user-images.githubusercontent.com/4082983/56189040-8dddf400-6059-11e9-9809-7c4ea780e79d.png)

**Comment by mawennan** [comment]
2019-04-16 15:36:15,000 ERROR Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.nacos.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.nacos.svc.cluster.local:8848]
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:211)
	at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectmetrics(PerformanceLoggerThread.java:123)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2019-04-16 15:37:22,945 ERROR ########## [serverlist] self ip nacos-0.nacos-headless.nacos.svc.cluster.local.:8848 not in serverlist [nacos-0.nacos-headless.nacos.svc.cluster.local:8848, nacos-1.nacos-headless.nacos.svc.cluster.local:8848, nacos-2.nacos-headless.nacos.svc.cluster.local:8848, nacos-0.nacos-headless.nacos.svc.cluster.local.:8848]
