### ISSUE TITLE
unable to find local peer: nacos-service-cf57bbd8-ccfbl:8848, all peers: [nacos-service.dev-app.svc.cluster.local:8848]

### ISSUE THREAD

**Issue by maomao-cloud** [nacos-group/nacos-k8s#122]
详细错误信息：
```
java.lang.IllegalStateException: unable to find local peer: nacos-service-cf57bbd8-ccfbl:8848, all peers: [nacos-service.dev-app.svc.cluster.local:8848]
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:224)
	at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectMetrics(PerformanceLoggerThread.java:100)
	at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)```
我的编排：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-app
  name: nacos-service
  labels:
    app: nacos-service
spec:
  selector:
    matchLabels:
      app: nacos-service
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos-service
    spec:
      containers:
        - name: nacos-service
          imagePullPolicy: Always
          image: nacos/nacos-server:1.2.0
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: NACOS_REPLICAS
              value: "1"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-service.dev-app.svc.cluster.local:8848"
          volumeMounts:
            - name: nacos-data
              mountPath: /home/nacos/data
            - name: nacos-log
              mountPath: /home/nacos/logs
      volumes:
        - name: nacos-data
          hostPath:
            path: /www/k3s/local_data/nacos/data
        - name: nacos-log
          hostPath:
            path: /www/k3s/local_data/nacos/log
```

**Comment by maomao-cloud** [comment]
我只打算启动一个单实例的nacos服务用于开发测试

**Comment by paderlol** [comment]
你用的deployment啊，只能用statefulset，这是有状态应用

**Comment by paderlol** [comment]
只想启动一个，为什么不用docker？而且为什么要用集群模式启动？

**Comment by maomao-cloud** [comment]
我在用k3s搭建一个小型开发环境，用k3s统一管理所有服务方便一些

**Comment by paderlol** [comment]
额，那和你用不用deployment没有必然关系吧？

**Comment by maomao-cloud** [comment]
恩，没有，我以为可以以无状态形式创建。谢谢你

**Comment by paderlol** [comment]
应该的，因为nacos是有状态应用不能用状态创建，而且内部对ip或者域名有依赖，所以deployment无法满足的
