### ISSUE TITLE
unable to find local peer

### ISSUE THREAD

**Issue by kinserlin** [nacos-group/nacos-k8s#13]
nacos启动后报错，已经换成k8s v1.12.2版本：  
```
NAME            STATUS                     ROLES    AGE   VERSION
192.168.1.130   Ready,SchedulingDisabled   master   28m   v1.12.2
192.168.1.131   Ready                      node     28m   v1.12.2
192.168.1.132   Ready                      node     28m   v1.12.2
```  
日志：
```
java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.default.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848]
        at com.alibaba.nacos.naming.raft.PeerSet.local(PeerSet.java:191)
        at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectmetrics(PerformanceLoggerThread.java:114)
        at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)  
```  
```
NAME                                          READY   STATUS    RESTARTS   AGE   IP           NODE            NOMINATED NODE
pod/mysql-master-m4j8r                        1/1     Running   0          20m   172.20.1.5   192.168.1.131   <none>
pod/mysql-slave-xz67m                         1/1     Running   0          20m   172.20.2.5   192.168.1.132   <none>
pod/nacos-0                                   1/1     Running   0          19m   172.20.1.6   192.168.1.131   <none>
pod/nacos-1                                   1/1     Running   0          19m   172.20.2.6   192.168.1.132   <none>
pod/nfs-client-provisioner-659fdbfdbb-ph6r6   1/1     Running   0          22m   172.20.2.4   192.168.1.132   <none>

NAME                                 DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES                            SELECTOR
replicationcontroller/mysql-master   1         1         1       20m   master       nacos/nacos-mysql-master:latest   name=mysql-master
replicationcontroller/mysql-slave    1         1         1       20m   slave        nacos/nacos-mysql-slave:latest    name=mysql-slave

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/kubernetes       ClusterIP   10.68.0.1      <none>        443/TCP    33m   <none>
service/mysql-master     ClusterIP   10.68.72.159   <none>        3306/TCP   20m   name=mysql-master
service/mysql-slave      ClusterIP   10.68.125.87   <none>        3306/TCP   20m   name=mysql-slave
service/nacos-headless   ClusterIP   None           <none>        8848/TCP   19m   app=nacos

NAME                                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS               IMAGES                                                   SELECTOR
deployment.apps/nfs-client-provisioner   1         1         1            1           22m   nfs-client-provisioner   quay.io/external_storage/nfs-client-provisioner:latest   app=nfs-client-provisioner

NAME                                                DESIRED   CURRENT   READY   AGE   CONTAINERS               IMAGES                                                   SELECTOR
replicaset.apps/nfs-client-provisioner-659fdbfdbb   1         1         1       22m   nfs-client-provisioner   quay.io/external_storage/nfs-client-provisioner:latest   app=nfs-client-provisioner,pod-template-hash=659fdbfdbb

NAME                     DESIRED   CURRENT   AGE   CONTAINERS   IMAGES
statefulset.apps/nacos   2         2         19m   nacos        registry-vpc.cn-shanghai.aliyuncs.com/yqcloud-tools/nacos-server:latest
```

**Comment by von1994** [comment]
Had you solved this question?

**Comment by kengan** [comment]
java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.default.svc.cluster.local.:8848, all peers: [nacos-0.nacos-headless.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848, nacos-2.nacos-headless.default.svc.cluster.local:8848]


1.1.3镜像 部署在k8s 1.14上，出这个错，请问如何解决
