### ISSUE TITLE
有没有本地的nacos正常，部署到K8s上之后乱码了？

### ISSUE THREAD

**Issue by crqcheer** [nacos-group/nacos-k8s#163]
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"      |�=�0������ئ��KE�v�kr�`ZŤ.���ܼ�{ޏ�[,��y[��f��f3k��1���BPO	��_V����y�X!R�<�ؐ=��VLӼP��d��Ǵ���[�e)l!�R�ԥ�b�Je�t���s��N�YG�mj�,�@����~����7/=E4����  �� v8�^�   "; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:685) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2403) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:672) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4662) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4511) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.alibaba.nacos.common.utils.JacksonUtils.toObj(JacksonUtils.java:159) ~[nacos-common-1.3.2.jar:?]
	... 25 more

**Comment by paderlol** [comment]
需要更多信息,这个没法判断,是否跟数据库编码有关系,因为k8s本身使用的是官方release的包作为镜像.

**Comment by linsword20** [comment]
我也乱码 走ingress就乱码  通过nodeport就不乱码

**Comment by paderlol** [comment]
Ingress可能也有编码问题

**Comment by linsword20** [comment]
> Ingress可能也有编码问题

我们其他服务一直在用这个ingress controller的
而且通过postman或者curl httpclient直接访问nacos  返回正常 使用nacos 的客户端拿到就乱码

**Comment by crqcheer** [comment]
> 我也乱码 走ingress就乱码 通过nodeport就不乱码 @paderlol

把微服务的的实例部署在k8s内网环境就行了，我是通过外网本地注册到k8s中的nacos就会乱码，微服务部署在k8s内网环境就没问题了，你也试试在内网环境注册试一下，ps：nacos注册地址使用k8s的svc地址

**Comment by linsword20** [comment]
> 把微服务的的实例部署在k8s内网环境就行了，我是通过外网本地注册到k8s中的nacos就会乱码，微服务部署在k8s内网环境就没问题了，你也试试在内网环境注册试一下，ps：nacos注册地址使用k8s的svc地址

嗯 不过我们暂时会存在k8s外的服务访问 估计还是ingress controller和nacos的http请求组件之间的兼容性问题

**Comment by linsword20** [comment]
怎么关了呢  这本身就是有问题呀 @crqcheer

**Comment by paderlol** [comment]
这个乱码问题可以提到nacos 去反应下
