### ISSUE TITLE
naming-server.log : protect threshold reached, return all ips,有遇到相同问题的吗?

### ISSUE THREAD

**Issue by shadowhunterhh** [nacos-group/nacos-k8s#169]
nacos的naming-server.log中报错2020-10-31 11:24:21,292 WARN protect threshold reached, return all ips, service: DEFAULT_GROUP@@providers:com.datedu.homework.service.TeaHomeworkService
同时服务的log日志报错
2020-10-31 00:01:14.152 [com.alibaba.nacos.client.naming.updater] WARN  com.alibaba.nacos.client.naming - failed to request http://172.17.0.17:8848/nacos/v1/ns/instance/list?healthyOnly=false&namespaceId=public&clientIP=127.0.0.1&serviceName=DEFAULT_GROUP%40%40providers%3Acom.datedu.base.service.BaseClassService&udpPort=46005&encoding=UTF-8 from 172.17.0.17
2020-10-31 00:01:14.154 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
请问这是什么问题引起的？有大神知道该如何解决吗？
nacos  server版本1.3.1，使用集群部署

**Comment by paderlol** [comment]
Server没访问通？

**Comment by shadowhunterhh** [comment]
> Server没访问通？

服务器之间内网、外网都是通的

**Comment by paderlol** [comment]
可你的接口就是反馈的超时，那就是不通啊

**Comment by shadowhunterhh** [comment]
> 可你的接口就是反馈的超时，那就是不通啊

我同时使用了nacos做配置中心和注册中心，这个情况出现挺久了，但是没影响使用。这个接口报错只是注册中心超时的报错是吗？我准备排查一下。

**Comment by paderlol** [comment]
可能是其中某一个节点挂了

**Comment by shadowhunterhh** [comment]
> 可能是其中某一个节点挂了

可是报错时我查看节点列表全都是up，并且我可以正常访问接口报错的那台服务器的nacos web端。您知道这个报错是配置中心的报错还是服务中心的报错吗？

**Comment by paderlol** [comment]
注册中心

**Comment by paderlol** [comment]
长时间没有回复暂时关闭issue
