### ISSUE TITLE
使用cluster模式，连接阿里云的Mysql，只有一个节点能连接上mysql，其它两个节点连接超时

### ISSUE THREAD

**Issue by jkme1987** [nacos-group/nacos-k8s#178]
使用nacos-quick-start部署nacos（1.3.0版本）集群，节点为3。配置完ingress后通过域名访问，在集群管理--节点列表nacos-2节点为UP，nacos-0与nacos-1为DOWN。
查看容器日志，发现nacos-0与nacos-1报错，报错信息：
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:191)
        at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        ... 40 common frames omitted
Caused by: java.lang.IllegalStateException: No DataSource set
        at org.springframework.util.Assert.state(Assert.java:73)
        at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:77)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:480)
        at com.alibaba.nacos.config.server.service.repository.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:702)
        at com.alibaba.nacos.config.server.service.dump.DumpAllProcessor.process(DumpTask.java:198)
        at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:249)
        at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:155)
        ... 48 common frames omitted

请问该如何解决？

![1](https://user-images.githubusercontent.com/13174382/100061213-b39fc180-2e68-11eb-94cb-5adc9e435d59.png)

**Comment by paderlol** [comment]
你要看你那个节点的网络是否能连接数据库

**Comment by jkme1987** [comment]
问题刚刚解决了，原来是内部网络出问题了。
