### ISSUE TITLE
java.lang.IllegalStateException: can not find peer: nacos-2.nacos-headless.nsfly-nacos.svc.cluster.local:8848

### ISSUE THREAD

**Issue by wukun1994** [nacos-group/nacos-k8s#180]
k8s部署nacos1.3.2版本集群出现如下问题

java.lang.IllegalStateException: can not find peer: nacos-2.nacos-headless.nsfly-nacos.svc.cluster.local:8848
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.receivedVote(RaftCore.java:494)
        at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:88)
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

说明：网络通信是好的

**Comment by paderlol** [comment]
看一下raft和cluster日志有什么问题

**Comment by wukun1994** [comment]
![image](https://user-images.githubusercontent.com/26002869/100407147-981ffb00-30a2-11eb-8515-eaa9a45b49d5.png)
![Uploading image.png…]()
从日志看是连接不上，但是我刚刚试了网络试通的

**Comment by wukun1994** [comment]
我遇到的问题应该跟之前有个人提出的问题一样

**Comment by wukun1994** [comment]
![Uploading image.png…]()

**Comment by paderlol** [comment]
你看下是否和这个issue相关#166

**Comment by paderlol** [comment]
same issue #206
