### ISSUE TITLE
nacos服务间歇503 ， 配置中心可用 

### ISSUE THREAD

**Issue by Jackjun724** [nacos-group/nacos-k8s#183]
K8S集群的nacos, 与仓库中的差距：MySQL修改为外部数据源，NFS改为AWS EFS。
使用了peer-finder，API接口间歇503接口

```log
2020-12-07 10:54:07.674 ERROR 7 --- [ing.beat.sender] com.alibaba.nacos.client.naming : [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"192.168.37.26","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":80,"scheduled":false,"serviceName":"DEFAULT_GROUP@@user","stopped":false,"weight":1.0}

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([http://nacos-headless.default:8848]) tried: failed to req API:http://nacos-headless.default:8848/nacos/v1/ns/instance/beat. code:503 msg: server is DOWN now, please try again later!
```

dashboard
<img width="840" alt="WeChat3eb6aba7bb4d23311e496c0afe218a94" src="https://user-images.githubusercontent.com/38455717/101305143-f3a97000-387c-11eb-87f4-97ccea160c00.png">

503 `server is DOWN now, please try again later!`

**Comment by paderlol** [comment]
建议不要使用peerfinder在AWS,直接自己配置,你这个错误看起来就是集群没有选举成功

**Comment by Jackjun724** [comment]
<img width="967" alt="WeChatb041467a32df77ab66f8e448281a2025" src="https://user-images.githubusercontent.com/38455717/101305588-f6f12b80-387d-11eb-8e52-7429591ec784.png">
这是在dashboard的看到的节点信息，另一个不在图中的节点信息看起来也是正常的，只是nacos-0看起来不太正常，是peerfinder的问题吗？而且之前都是正常的，昨天重启了某个node服务器，就变成这样了

**Comment by Jackjun724** [comment]
最后一个节点的元数据
```json
{
    "adWeight": "0",
    "lastRefreshTime": 1607311037729,
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-1.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 7
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
```
貌似指向了问题节点

**Comment by paderlol** [comment]
那不是peerfinder导致的
重启是目前选举有个问题导致的,1.4.1会修复

**Comment by paderlol** [comment]
重启或者扩容缩容都会出现这个问题

**Comment by paderlol** [comment]
你看下是否和这个issue相关#166

**Comment by Jackjun724** [comment]
重启后找peer node总是找不全，两个能正常发现，一个只能发现3个中的两个，关掉peer-finder了。

**Comment by Jackjun724** [comment]
去调peer-finder-plugin也是一样的报错

**Comment by Jackjun724** [comment]
```json
{
    "adWeight": "0",
    "lastRefreshTime": 1607315795916,
    "naming": {
        "voteFor": "nacos-0.nacos-headless.default.svc.cluster.local:8848",
        "ip": "nacos-0.nacos-headless.default.svc.cluster.local:8848",
        "heartbeatDueMs": 4500,
        "term": 2,
        "leaderDueMs": 19628,
        "state": "LEADER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-2.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 9
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
```
```json
{
    "adWeight": "0",
    "lastRefreshTime": 1607315793915,
    "naming": {
        "voteFor": "nacos-0.nacos-headless.default.svc.cluster.local:8848",
        "ip": "nacos-1.nacos-headless.default.svc.cluster.local:8848",
        "heartbeatDueMs": 5000,
        "term": 2,
        "leaderDueMs": 19521,
        "state": "FOLLOWER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "raftGroupMember": [
                    "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-1.nacos-headless.default.svc.cluster.local:7848"
                ]
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
```
```json
{
    "adWeight": "0",
    "lastRefreshTime": 1607315227579,
    "naming": {
        "ip": "nacos-2.nacos-headless.default.svc.cluster.local:8848",
        "heartbeatDueMs": 5000,
        "term": 0,
        "leaderDueMs": 15993,
        "state": "FOLLOWER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-2.nacos-headless.default.svc.cluster.local:7848",
                    "nacos-0.nacos-headless.default.svc.cluster.local:7848"
                ],
                "term": 9
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
```
三个节点的数据

**Comment by Jackjun724** [comment]
在 naming-raft.log里面看到了 nacos-2的日志如下
```
ERROR NACOS-RAFT vote failed: 500, url: http://nacos-0.nacos-headless.default.svc.cluster.local:8848/nacos/v1/ns/raft/vote
```
而对应在nacos-0的nacos.log出现如下日志
```
java.lang.IllegalStateException: old raft protocol already stop
        at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by Jackjun724** [comment]
降级到v1.3.4了。没问题了，不知道jraft是怎么升级的

**Comment by paderlol** [comment]
没有1.3.4吧？只有1.3.2，并且这个不是jraft升级，是Nacos选举的问题，会发生在扩容缩容或者重启上面

**Comment by Jackjun724** [comment]
是v1.3.2
