### ISSUE TITLE
Get http://172.17.0.2:8848/nacos/v1/ns/operator/servers: dial tcp 172.17.0.2:8848: connect: connection refused

### ISSUE THREAD

**Issue by Mnicca** [nacos-group/nacos-k8s#273]
```
kubectl get po -o wide
#结果
NAME                              READY   STATUS    RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
nacos-0                           1/1     Running   0          14m   172.17.0.3   kube-node2    <none>           <none>
nacos-1                           1/1     Running   0          14m   172.17.0.3   kube-master   <none>           <none>
nacos-2                           1/1     Running   0          14m   172.17.0.3   kube-node1    <none>           <none>
nacos-operator-647bf68498-rfxqd   1/1     Running   0          18m   172.17.0.2   kube-node2    <none>           <none>
```
这个是正常的，但是
```
kubectl get nacos
#结果
NAME    REPLICAS   READY    TYPE      DBTYPE   VERSION   CREATETIME
nacos   3          Failed   cluster                      2021-12-15T05:58:25Z
```
这个状态是Filed。
```
kubectl get nacos nacos -o yaml -w
#结果
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  creationTimestamp: "2021-12-15T05:58:25Z"
  generation: 1
  name: nacos
  namespace: default
  resourceVersion: "1822711"
  selfLink: /apis/nacos.io/v1alpha1/namespaces/default/nacos/nacos
  uid: 7cd6ac72-ede6-4046-8cf5-5d3378e69442
spec:
  image: nacos/nacos-server:1.4.1
  replicas: 3
  type: cluster
status:
  event:
  - code: 401
    firstAppearTime: "2021-12-15T06:01:26Z"
    lastTransitionTime: "2021-12-15T06:22:07Z"
    message: 'Get http://172.17.0.3:8848/nacos/v1/ns/operator/servers: dial tcp 172.17.0.3:8848:
      connect: connection refused[]'
    status: false
  phase: Failed
```
请问一下这个大概是什么问题，有没有大佬帮忙看一下？

**Comment by shenkonghui** [comment]
@Mnicca 从message信息看，nacos服务的端口没有打开。在集群节点上访问http://172.17.0.3:8848/nacos/v1/ns/operator/servers看看能不能访问的通？ 
如果还是不能访问的通需要查看对应的nacos节点的日志了，kubectl logs <pod>

**Comment by senhao-xu** [comment]
我也遇到了相同的问题，查看了nacos-pod的日志

```bash
14:39:32.808 [main] DEBUG org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - Application failed to start due to an exception
org.springframework.boot.context.config.ConfigDataLocationNotFoundException: Config data location '/home/nacos/init.d/' cannot be found
	at org.springframework.boot.context.config.ConfigDataEnvironment.checkMandatoryLocations(ConfigDataEnvironment.java:383)
	at org.springframework.boot.context.config.ConfigDataEnvironment.applyToEnvironment(ConfigDataEnvironment.java:326)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:233)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
14:39:32.811 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Config data location '/home/nacos/init.d/' does not exist

```

operator logs 

```bash
I1115 06:50:16.355271       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:50:16.370626       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:50:31.372978       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:50:31.394130       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:50:46.389233       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:50:46.407323       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:51:01.406080       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:51:01.431019       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:51:16.423622       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
I1115 06:51:16.451840       1 nacos_controller.go:127] controllers/Nacos "msg"="painc"  "code"=401 "msg"="Get http://10.244.0.191:8848/nacos/v1/ns/operator/servers: dial tcp 10.244.0.191:8848: connect: connection refused[]"
```

**Comment by senhao-xu** [comment]
我测试了config/samples/nacos.yaml文件，v2.0.3版本可以启动，但是降低版本就不行了，这个问题需要在上面进行标注或向下兼容

**Comment by ldsdsy** [comment]
我也遇到了这种情况，在集群节点上访问还是拒绝连接，看日志的话全都是 INFO Nacos is starting... 不太清楚具体原因在哪

**Comment by fyqls** [comment]
2个问题:
1.  这个api不对，我用的nacos 2.2.0版本api变成了nacos/v1/core/cluster/nodes
2.   这个operator写的有点问题，初始化的结束立马就进行了健康检查，且没有重试机制。nacos服务可能当时还没有ready
