### ISSUE TITLE
访问nacos的服务列表报错

### ISSUE THREAD

**Issue by jiangzhikele** [nacos-group/nacos-k8s#32]
server is STARTING now，please try  again later！
查看日志后，
[root@nacos-0 logs]# tail naming-raft.log 
2019-04-30 09:15:45,000 WARN [IS LEADER] no leader is available now!

2019-04-30 09:16:00,001 WARN [IS LEADER] no leader is available now!

2019-04-30 09:16:15,000 WARN [IS LEADER] no leader is available now!

2019-04-30 09:16:30,000 WARN [IS LEADER] no leader is available now!

2019-04-30 09:16:45,000 WARN [IS LEADER] no leader is available now!

[root@nacos-0 logs]# tail naming-ephemeral.log 
2019-04-30 09:17:28,671 INFO waiting server list init...

2019-04-30 09:17:29,671 INFO waiting server list init...

2019-04-30 09:17:30,672 INFO waiting server list init...

2019-04-30 09:17:31,672 INFO waiting server list init...

2019-04-30 09:17:32,672 INFO waiting server list init...

怎么解决

**Comment by paderlol** [comment]
请说明下使用的K8s以及Nacos的版本，以及如何配置的

**Comment by jiangzhikele** [comment]
k8s是1.12.4，nacos用的是您最新的镜像。nacos使用的是最简单的安装，没有装nfs

**Comment by jiangzhikele** [comment]
![image](https://user-images.githubusercontent.com/38905258/56936599-de118780-6b2a-11e9-8c7b-41badd8100a7.png)

**Comment by paderlol** [comment]
看一下nacos-server.log的日志

**Comment by paderlol** [comment]
用的quickstart这种启动方式吗?

**Comment by jiangzhikele** [comment]
用的是quickstart启动方式
[root@nacos-0 logs]# tail naming-server.log 
java.lang.IllegalArgumentException: server: nacos-0.nacos-headless.default.svc.cluster.local.:8848 is not in serverlist
	at com.alibaba.nacos.naming.cluster.ServerListManager.onReceiveServerStatus(ServerListManager.java:193)
	at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:411)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


您说的nacos-server.log日志在什么地方？

**Comment by paderlol** [comment]
就是在你看的这些日志的同一个目录下面,你是不是自己用了特殊的命名空间？

**Comment by paderlol** [comment]
我看到了 你这个域名后面nacos-0.nacos-headless.default.svc.cluster.local. 多了一个点 这个不确定是K8s网络问题,有一些高版本就有这个问题,要么把k8s降级,还有一种把你配置的serverlist的地方每个域名后面都加.

**Comment by jiangzhikele** [comment]
好了   解决了  是这个.的问题。感谢

**Comment by yaofeng** [comment]
这个“.”的问题是怎么引起的呢，为什么获取出来的主机名多了这个“.”？
