### ISSUE TITLE
server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized] 

### ISSUE THREAD

**Issue by dotaZealot** [nacos-group/nacos-k8s#358]
环境
- k8s
- Centos 8
- Nacos镜像 2.1.0
- Mysql 8

部署方式
- 使用官方STS方式部署
- 为了方便跨级群Prometheus抓取，开启了hostNetwork dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

**问题1：**
curl http://nacos-0.nacos-headless.default.svc.cluster.local:8848/nacos/v1/ns/operator/cluster/state
server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

**问题2**
cat logs/nacos.log
2022-11-16 20:50:15,276 ERROR CONSOLE /nacos/v1/ns/operator/cluster/state

java.lang.IllegalStateException: unable to find local peer: localhost.vm:8848, all peers: []
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:292)
        at com.alibaba.nacos.naming.core.ServiceManager.getMySelfClusterState(ServiceManager.java:287)
        at com.alibaba.nacos.naming.controllers.OperatorController.getClusterStates(OperatorController.java:296)
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source)

**Comment by AndreChou** [comment]
我也是这些问题，搞了好久啊，难过。。。

**Comment by LinkMaq** [comment]
把STS中的dnspolicy改成`ClusterFirstWithHostNet`试下
