### ISSUE TITLE
k8s部署nacos2.0.3集群一直报错：java.lang.IllegalStateException: can not find peer: nacos-2.nacos-headless.default.svc.cluster.local:8848

### ISSUE THREAD

**Issue by foreverloveali** [nacos-group/nacos-k8s#455]
nacos.log日志报错如下：
![image](https://github.com/nacos-group/nacos-k8s/assets/65100093/11e061b2-e662-4cea-8121-b6324c3506d0)
naming-raft日志报错如下：
![image](https://github.com/nacos-group/nacos-k8s/assets/65100093/60f5c50d-6ae1-49f3-a033-aef9637c84dc)

**Comment by foreverloveali** [comment]
其他两个节点识别不到nacos-0：
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: nacos-0.nacos-headless.default.svc.cluster.local
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:420)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:256)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213)
        ... 3 common frames omitted

**Comment by foreverloveali** [comment]
最新报错是其他两个节点识别不到nacos-0
