### ISSUE TITLE
k8s方式启动成功后，配置管理台可以使用，java无法连接

### ISSUE THREAD

**Issue by yeyuguang1** [nacos-group/nacos-k8s#49]
k8s启动3个StatefulSet，启动成功，配置台可用，
java连接报错server is STARTING now, please try again later!，查看日志naming-rafe.log,WARN [IS LEADER] no leader is available now!
进入pod检查， cluster.conf有三条，正常，ping也可以正常ping通。找不到原因了，请问有遇到过吗？使用的是nacos 1.0.0的tag打的镜像

**Comment by paderlol** [comment]
用的nfs启动方式吗？k8s版本查看下

**Comment by yeyuguang1** [comment]
自己搭的nfs，所以吧deployment的volumeClaimTemplates，改成了volume,hostpash的方式了，k8s版本是1.11.0的

**Comment by paderlol** [comment]
clusterip 设置为none没？

**Comment by yeyuguang1** [comment]
nacos-headless   ClusterIP   None             <none>        8848/TCP         1h

nacos-cloud-0                   1/1       Running   0          1h
nacos-cloud-1                   1/1       Running   0          12m
nacos-cloud-2                   1/1       Running   0          11m

nova-config    zhike-nacos.vanke.com                                                                      80        1

http://zhike-nacos.vanke.com/nacos/v1/ns/services/list访问报错server is STARTING now, please try again later!

日志naming-raft 2019-06-25 18:19:45,000 WARN [IS LEADER] no leader is available now!

**Comment by paderlol** [comment]
你这个域名不是用的statefulset吧？

**Comment by paderlol** [comment]
你这个域名是用的ingress吧，我说的是你每个pod的域，你需要确认你的本地获取的hostname是不是带了个点，

**Comment by paderlol** [comment]
如果是本地带了.就是dns的原因，需要解决下，或者把k8s升级到1.12

**Comment by yeyuguang1** [comment]
我只是给service放了一个ingress，通过pod的ip一样报错的
下面是我的deployment
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: zhike-cloud
  labels:
    app: nacos-cloud
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  #type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos-cloud
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: zhike-cloud
data:
  mysql.master.db.name: "nacos_devtest"
  mysql.master.port: "3306"
  mysql.slave.port: "3306"
  mysql.master.user: "yeyg"
  mysql.master.password: "YYUG#6og9n"
---
apiVersion: apps/v1
#kind: Deployment
kind: StatefulSet
metadata:
  name: nacos-cloud
  namespace: zhike-cloud
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos-cloud
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #          matchExpressions:
      #            - key: "app"
      #              operator: In
      #              values:
      #                - nacos
      #        topologyKey: "kubernetes.io/hostname"
      #serviceAccountName: nfs-client-provisioner
      initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plugindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: docker-repo.vanke.com/zhike/nacos:yeyg
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_MASTER_SERVICE_HOST
              value: "172.16.49.27"
            - name: MYSQL_MASTER_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.db.name
            - name: MYSQL_MASTER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.port
            #- name: MYSQL_SLAVE_SERVICE_PORT
            #  valueFrom:
            #    configMapKeyRef:
            #      name: nacos-cm
            #      key: mysql.slave.port
            - name: MYSQL_MASTER_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.user
            - name: MYSQL_MASTER_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.master.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
          readinessProbe:
            httpGet:
              port: client-port
              path: /nacos/v1/console/health/readiness
            initialDelaySeconds: 60
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: client-port
              path: /nacos/v1/console/health/liveness
            initialDelaySeconds: 60
            timeoutSeconds: 3
          volumeMounts:
            - name: plugindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
      volumes:
        - name: plugindir
          hostPath:
            path: /app/nfs-data/nacos/plugins/peer-finder
        - name: datadir
          hostPath:
            path: /app/nfs-data/nacos/data
        - name: logdir
          hostPath:
            path: /app/nfs-data/nacos/log
  #volumeClaimTemplates:
  #  - metadata:
  #      name: plugindir
  #      annotations:
  #        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #    spec:
  #      accessModes: [ "ReadWriteMany" ]
  #      resources:
  #        requests:
  #          storage: 5Gi
  #  - metadata:
  #      name: datadir
  #      annotations:
  #        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #    spec:
  #      accessModes: [ "ReadWriteMany" ]
  #      resources:
  #        requests:
  #          storage: 5Gi
  #  - metadata:
  #      name: logdir
  #      annotations:
  #        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  #    spec:
  #      accessModes: [ "ReadWriteMany" ]
  #      resources:
  #        requests:
  #          storage: 5Gi
  selector:
    matchLabels:
      app: nacos-cloud


[root@nacos-cloud-0 conf]# cat cluster.conf 

nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local:8848
nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local:8848
nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local:8848
[root@nacos-cloud-0 conf]# ping nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local
PING nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23) 56(84) bytes of data.
64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=1 ttl=64 time=0.039 ms
64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=2 ttl=64 time=0.027 ms
^V64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=3 ttl=64 time=0.027 ms
^C
--- nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.027/0.031/0.039/0.005 ms
[root@nacos-cloud-0 conf]# ping nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local
PING nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local (172.33.13.6) 56(84) bytes of data.
64 bytes from nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local (172.33.13.6): icmp_seq=1 ttl=62 time=1.44 ms
64 bytes from nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local (172.33.13.6): icmp_seq=2 ttl=62 time=1.25 ms
^C
--- nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.250/1.347/1.445/0.104 ms
[root@nacos-cloud-0 conf]# ping nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local
PING nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local (172.33.85.28) 56(84) bytes of data.
64 bytes from nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local (172.33.85.28): icmp_seq=1 ttl=62 time=0.958 ms
^C
--- nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
这个都是通的


/etc/hosts文件
[root@nacos-cloud-0 conf]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.33.9.23	nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local	nacos-cloud-0

/etc/hostname文件
[root@nacos-cloud-0 conf]# cat /etc/hostname 
nacos-cloud-0

[root@nacos-cloud-0 conf]# ping nacos-cloud-0 
PING nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23) 56(84) bytes of data.
64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=1 ttl=64 time=0.031 ms
64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=2 ttl=64 time=0.026 ms
64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=3 ttl=64 time=0.029 ms
^C64 bytes from nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local (172.33.9.23): icmp_seq=4 ttl=64 time=0.027 ms

**Comment by paderlol** [comment]
我说的是你看下日志 nacos.raft日志

**Comment by yeyuguang1** [comment]
-rw-r--r-- 1 root root 1367136 Jun 25 18:58 access_log.2019-06-25.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 cmdb-main.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 config-acl.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 config-app.log
-rw-r--r-- 1 root root   20188 Jun 25 16:57 config-client-request.log
-rw-r--r-- 1 root root    1728 Jun 25 18:02 config-dump.log
-rw-r--r-- 1 root root  107469 Jun 25 18:02 config-fatal.log
-rw-r--r-- 1 root root  369474 Jun 25 18:58 config-memory.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 config-notify.log
-rw-r--r-- 1 root root    1788 Jun 25 16:47 config-pull-check.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 config-pull.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 config-sdk-request.log
-rw-r--r-- 1 root root  260170 Jun 25 18:58 config-server.log
-rw-r--r-- 1 root root  111335 Jun 25 16:47 config-trace.log
-rw-r--r-- 1 root root    1532 Jun 25 18:57 nacos_gc.log.0.current
-rw-r--r-- 1 root root  500413 Jun 25 18:52 nacos.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-cache.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-debug.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-device.log
-rw-r--r-- 1 root root  639076 Jun 25 18:58 naming-ephemeral.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-event.log
-rw-r--r-- 1 root root    3392 Jun 25 18:58 naming-performance.log
-rw-r--r-- 1 root root   40687 Jun 25 18:58 naming-push.log
-rw-r--r-- 1 root root   87377 Jun 25 18:58 naming-raft.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-router.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-rt.log
-rw-r--r-- 1 root root  150435 Jun 25 18:58 naming-server.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-tag.log
-rw-r--r-- 1 root root       0 Jun 25 14:04 naming-tenant.log
-rw-r--r-- 1 root root    1905 Jun 25 18:02 start.out

没有nacos.raft日志
nacos.log有的
2019-06-25 18:07:23,113 INFO The server IP list of Nacos is [nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local:8848, nacos-cloud-1.nacos-headless.zhike-cloud.svc.cluster.local:8848, nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local:8848]
2019-06-25 18:07:23,132 INFO Starting Nacos v1.0.0 on nacos-cloud-2.nacos-headless.zhike-cloud.svc.cluster.local with PID 33 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)
2019-06-25 18:07:23,135 INFO No active profile set, falling back to default profiles: default
2019-06-25 18:07:24,122 INFO Nacos is starting...
2019-06-25 18:07:25,128 INFO Nacos is starting...
2019-06-25 18:07:26,152 INFO Nacos is starting...

2019-06-25 18:07:26,546 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$c6ec92e2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-06-25 18:07:26,697 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2019-06-25 18:07:26,704 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@162be91c' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-06-25 18:07:26,713 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$ebc13594] i not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-06-25 18:07:26,725 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] isnot eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-06-25 18:07:27,160 INFO Nacos is starting...
2019-06-25 18:07:27,456 INFO Tomcat initialized with port(s): 8848 (http)
2019-06-25 18:07:27,487 INFO Initializing ProtocolHandler ["http-nio-8848"]
2019-06-25 18:07:27,511 INFO Starting service [Tomcat]
2019-06-25 18:07:27,512 INFO Starting Servlet Engine: Apache Tomcat/9.0.13
2019-06-25 18:07:27,539 INFO The AR based Apache Tomcat Native library which allows optimal performance in production environmets was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2019-06-25 18:07:27,679 INFO Initializing Spring embedded WebApplicationContext
2019-06-25 18:07:27,679 INFO Root WebApplicationContext: initialization completed in 4446 ms
2019-06-25 18:07:28,164 INFO Nacos is starting...
2019-06-25 18:07:28,731 INFO Use Mysql as the driver
2019-06-25 18:07:29,168 INFO Nacos is starting...
2019-06-25 18:07:30,173 INFO Nacos is starting...
2019-06-25 18:07:31,178 INFO Nacos is starting...
2019-06-25 18:07:31,338 INFO Initializing ExecutorService 'applicationTaskExecutor'
2019-06-25 18:07:31,609 INFO Adding welcome page: class path resource [static/index.html]
2019-06-25 18:07:32,043 INFO Creating filter chain: Ant [pattern='/'], []
2019-06-25 18:07:32,046 INFO Creating filter chain: Ant [pattern='/**/*.css'], []
2019-06-25 18:07:32,049 INFO Creating filter chain: Ant [pattern='/**/*.js'], []
2019-06-25 18:07:32,049 INFO Creating filter chain: Ant [pattern='/**/*.html'], []
2019-06-25 18:07:32,052 INFO Creating filter chain: Ant [pattern='/**/*.map'], []
2019-06-25 18:07:32,052 INFO Creating filter chain: Ant [pattern='/**/*.svg'], []
2019-06-25 18:07:32,055 INFO Creating filter chain: Ant [pattern='/**/*.png'], []
2019-06-25 18:07:32,056 INFO Creating filter chain: Ant [pattern='/**/*.ico'], []
2019-06-25 18:07:32,056 INFO Creating filter chain: Ant [pattern='/console-fe/public/**'], []
2019-06-25 18:07:32,056 INFO Creating filter chain: Ant [pattern='/v1/auth/login'], []
2019-06-25 18:07:32,056 INFO Creating filter chain: Ant [pattern='/v1/console/health/**'], []
2019-06-25 18:07:32,056 INFO Creating filter chain: Ant [pattern='/v1/cs/**'], []
2019-06-25 18:07:32,057 INFO Creating filter chain: Ant [pattern='/v1/ns/**'], []
2019-06-25 18:07:32,057 INFO Creating filter chain: Ant [pattern='/v1/cmdb/**'], []
2019-06-25 18:07:32,061 INFO Creating filter chain: Ant [pattern='/actuator/**'], []
2019-06-25 18:07:32,061 INFO Creating filter chain: Ant [pattern='/v1/console/server/**'], []
2019-06-25 18:07:32,111 INFO Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@379ce046, org.springframework.security.web.context.SecurityContextPersistenceFilter@756b58a7, org.springframework.security.web.header.HeaderWriterFilter@7ea899a9, org.springframework.security.web.authentication.logout.LogoutFilter@61e7bf2f, com.alibaba.nacos.console.filter.JwtAuthenticationTokenFilter@701bc94e, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@68b58644, org.springframework.security.web.servletapi.SecurityContextHolderAwareReqestFilter@d48673, org.springframework.security.web.authentication.AnonymousAuthenticationFiter@3d8b319e, org.springframework.security.web.session.SessionManagementFilter@327ed9f, org.springframework.security.web.access.ExceptionTranslationFilter@74db12c2,org.springframework.security.web.access.intercept.FilterSecurityInterceptor@68fe48d7]
2019-06-25 18:07:32,162 INFO Exposing 2 endpoint(s) beneath base path '/actuator'
2019-06-25 18:07:32,196 INFO Nacos is starting...
2019-06-25 18:07:32,211 INFO Initializing ExecutorService 'taskScheduler'
2019-06-25 18:07:32,294 INFO Starting ProtocolHandler ["http-nio-8848"]
2019-06-25 18:07:32,296 INFO Using a shared selector for servlet write/read
2019-06-25 18:07:32,407 INFO Tomcat started on port(s): 8848 (http) with context path '/nacos'
2019-06-25 18:07:32,417 INFO Started Nacos in 11.193 seconds (JVM running for 12.267)
2019-06-25 18:07:32,417 INFO Nacos Log files: /home/nacos/logs/
2019-06-25 18:07:32,417 INFO Nacos Conf files: /home/nacos/conf/
2019-06-25 18:07:32,417 INFO Nacos Data files: /home/nacos/data/
2019-06-25 18:07:32,417 INFO Nacos started successfully in cluster mode.
2019-06-25 18:07:33,082 INFO Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-06-25 18:07:33,082 INFO Initializing Servlet 'dispatcherServlet'
2019-06-25 18:07:33,098 INFO Completed initialization in 16 ms
2019-06-25 18:16:17,764 INFO [capacityManagement] start correct usage
2019-06-25 18:16:17,798 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:16:18,021 WARN clearConfigHistory start
2019-06-25 18:17:29,782 INFO [capacityManagement] start correct usage
2019-06-25 18:17:29,815 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:17:30,089 WARN clearConfigHistory start
2019-06-25 18:26:29,240 INFO Expired JWT token.
 start correct usage
2019-06-25 18:26:17,828 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:26:18,022 WARN clearConfigHistory start
2019-06-25 18:26:29,259 ERRR Responding with unauthorized error. Message - Full authentication is required to access this resource
2019-06-25 18:27:29,818 INFO [capacityManagement] start correct usage
2019-06-25 18:27:29,846 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:27:30,093 WARN clearConfigHistory start
2019-06-25 18:36:17,831 INFO [capacityManagement] start correct usage
2019-06-25 18:36:17,861 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:36:18,022 WARN clearConfigHistory start
2019-06-25 18:37:29,851 INFO [capacityManagement] start correct usage
2019-06-25 18:37:29,878 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:37:30,093 WARN clearConfigHistory start
2019-06-25 18:46:17,861 INFO [capacityManagement] start correct usage
2019-06-25 18:46:17,890 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:46:18,025 WARN clearConfigHistory start
2019-06-25 18:56:17,895 INFO [capacityManagement] start correct usage
2019-06-25 18:56:17,924 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:56:18,025 WARN clearConfigHistory start
2019-06-25 18:57:29,911 INFO [capacityManagement] start correct usage
2019-06-25 18:57:29,945 INFO [capacityManagement] end correct usage, cost: 0s
2019-06-25 18:57:30,103 WARN clearConfigHistory start

naming.raft日志
2019-06-25 19:04:45,000 WARN [IS LEADER] no leader is available now!
2019-06-25 19:05:00,000 WARN [IS LEADER] no leader is available now!
2019-06-25 19:05:15,001 WARN [IS LEADER] no leader is available now!
2019-06-25 19:05:30,000 WARN [IS LEADER] no leader is available now!
2019-06-25 19:05:45,000 WARN [IS LEADER] no leader is available now!
2019-06-25 19:06:00,000 WARN [IS LEADER] no leader is available now
2019-06-25 19:06:15,001 WARN [IS LEADER] no leader is available now!

**Comment by li-sen** [comment]
同样的问题 
```
2019-06-28 16:26:54,386 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00

2019-06-28 16:27:00,008 WARN [IS LEADER] no leader is available now!

2019-06-28 16:27:15,001 WARN [IS LEADER] no leader is available now!
```

**Comment by li-sen** [comment]
```

java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.xinyi-dev.svc.cluster.local.:8848, all peers: [nacos-1.nacos-headless.xinyi-dev.svc.cluster.local:8848, nacos-2.nacos-headless.xinyi-dev.svc.cluster.local:8848, nacos-0.nacos-headless.xinyi-dev.svc.cluster.local:8848]
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:211)
	at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectmetrics(PerformanceLoggerThread.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-28 16:30:30,001 ERROR Unexpected error occurred in scheduled task.
```

**Comment by li-sen** [comment]
pod 解析 nacos-0.nacos-headless.xinyi-dev.svc.cluster.local. 的ip是对啊 ，怎么会说找不到呢？

**Comment by paderlol** [comment]
你的dns有问题，域名多了个.

**Comment by li-sen** [comment]
这不是 statefulset 默认 headless 域名啊

**Comment by paderlol** [comment]
你要么切换版本到1.12，之前有小伙伴遇到过，说dns解析问题，你这个域名后面带了个. 正常是没有的

**Comment by li-sen** [comment]
k8s 为v1.13.5， 很多安装方式  kubelet 参数 默认都为 --cluster-domain=cluster.local. 
明显跟 k8s版本无关，算了 我自己改下 inicontaner 改下 /etc/hosts文件

**Comment by li-sen** [comment]
pr  以提交 ，我这边测试 没有问题。

**Comment by yeyuguang1** [comment]
....我的查的dns没问题，网络也是通的，pod解析也对，启动也成功了，就是没有leader...找不到原因了。。。

**Comment by paderlol** [comment]
看看raft.log日志

> ....我的查的dns没问题，网络也是通的，pod解析也对，启动也成功了，就是没有leader...找不到原因了。。。

**Comment by yeyuguang1** [comment]
2019-06-28 18:04:56,359 INFO initializing Raft sub-system

2019-06-28 18:04:56,360 INFO raft notifier started

2019-06-28 18:04:56,282 INFO server list is updated, new: 1 servers: [{"adWeight":0,"alive":false,"ip":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local","key":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local:8848","lastRefTime":0,"servePort":8848,"site":"unknown","weight":1}]

2019-06-28 18:04:56,372 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local","key":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]

2019-06-28 18:04:56,374 INFO finish loading all datums, size: 0 cost 14 ms.

2019-06-28 18:04:56,376 INFO cache loaded, datum count: 0, current term: 0

2019-06-28 18:04:56,376 INFO finish to load data from disk, cost: 16 ms.

2019-06-28 18:04:56,379 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000

2019-06-28 18:04:56,441 INFO add listener: com.alibaba.nacos.naming.domains.meta.

2019-06-28 18:04:58,079 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00

2019-06-28 18:05:01,278 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local","key":"nacos-cloud-0.nacos-headless.zhike-cloud.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]

2019-06-28 18:05:15,004 WARN [IS LEADER] no leader is available now!

**Comment by paderlol** [comment]
日志显示节点选举超时，看一下naming server的日志，有没有异常

**Comment by yeyuguang1** [comment]
2019-06-28 18:04:56,441 INFO listen for service meta change

2019-06-28 18:05:00,152 INFO [SERVER-INIT] got port: 8848

2019-06-28 18:05:00,152 INFO [SERVER-INIT] got path: /nacos

2019-06-28 18:05:01,278 INFO [NACOS-DISTRO] healthy server list changed, disable health check for 60000 ms from now on

2019-06-28 18:05:29,028 INFO [HEALTH-CHECK] health check is false

2019-06-28 18:06:01,281 INFO [NACOS-DISTRO] distro threshold restored and stable now, enable health check. current ratio: 1.0

2019-06-28 18:10:29,028 INFO [HEALTH-CHECK] health check is true

2019-06-28 18:15:29,028 INFO [HEALTH-CHECK] health check is true

2019-06-28 18:20:29,029 INFO [HEALTH-CHECK] health check is true

2019-06-28 18:25:29,029 INFO [HEALTH-CHECK] health check is true

**Comment by paderlol** [comment]
pod之间互相能ping通吗？

**Comment by yeyuguang1** [comment]
通的呀，都能正常ping通的

**Comment by paderlol** [comment]
用的quickstart还是nfs方式？

**Comment by yeyuguang1** [comment]
nfs的，上面我都提供了完整的yaml文件，只是把nfs改成了hostpath

**Comment by paderlol** [comment]
你看下日志是不是和上面的人一样的问题，如果是就重新拉去一下代码，他提交的pr解决了这个问题

**Comment by paderlol** [comment]
最好把所有日志都看下，或者直接看nacos.log，没有任何错误，我也办法判断

**Comment by yeyuguang1** [comment]
我看了他的，我dns没问题，我拉的事nacos1.0.0版本的，我重新试试最新版吧

**Comment by paderlol** [comment]
应该和镜像没关系的，现在是内部节点选举超时超时，说明pod之间通讯没成功，可你说没问题，你可以试着在nacos -0请求nacos-1任意接口，看看能请求通吗？

**Comment by yeyuguang1** [comment]
我去掉这个nacos/nacos-peer-finder-plugin 这个init插件，然后写死nacos_servers地址就启动成功没有问题

**Comment by paderlol** [comment]
好的，可以暂时不用那个插件吧

**Comment by yeyuguang1** [comment]
嗯嗯，感谢，暂时不用那个，那个就是为了动态改nacosservers用的…写死也好

**Comment by paderlol** [comment]
嗯，不客气，没帮上你😂，issue我关了
