### ISSUE TITLE
k8s部署nacos 集群，服务注册发现功能不可用  server is STARTING now, please try again later!

### ISSUE THREAD

**Issue by fengjian1585** [nacos-group/nacos-k8s#64]
k8s部署nacos 集群，服务注册发现功能不可用

2019-08-28 14:53:38,845 INFO receive config info: unknown#nacos-1.nacos-headless.test.svc.cluster.local.:8848#1566975218845#1

2019-08-28 14:53:38,845 ERROR [SERVER-STATUS] Exception while sending server status

java.lang.IllegalArgumentException: server: nacos-1.nacos-headless.test.svc.cluster.local.:8848 is not in serverlist
	at com.alibaba.nacos.naming.cluster.ServerListManager.onReceiveServerStatus(ServerListManager.java:198)
	at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:345)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

curl -X PUT 'http://nacos-headless:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

server is STARTING now, please try again later!

[root@nacos-1 nacos]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.254.3.99	nacos-1.nacos-headless.test.svc.cluster.local.	nacos-1

**Comment by paderlol** [comment]
你应该是使用本地的方式启动…这是由于k8s dns生成方式导致的，不是nacos的原因，如果你用的nfs的方式，脚本会解决这个问题，本地快速启动就需要你们自己处理下了。

**Comment by silverlight** [comment]
hi，我也遇到了相同的问题，能说一下具体的解决方案吗？

**Comment by paderlol** [comment]
关于这个问题是dns的问题，需要你们自己处理下，因为nacos内部会去比对地址域名，但是k8s有些版本是带根域名的，所以匹配不上，单机版自己去通过k8s的配置改变这个点，或者容器里面用脚本初始化的时候消除这个点。

**Comment by silverlight** [comment]
我的K8S版本是1.16，我不太明白具体需要配置DNS的什么才能解决这个问题。如果可以的话能说下具体方向吗，非常感谢~

**Comment by paderlol** [comment]
Cluster domain改成 cluster.local

**Comment by silverlight** [comment]
您说的是cluster.conf文件吗？现在改之前已经是 nacos-0.nacos-headless.default.svc.cluster.local:8848

**Comment by silverlight** [comment]
您说的是cluster.conf文件吗？现在改之前已经是 nacos-0.nacos-headless.default.svc.cluster.local:8848

**Comment by paderlol** [comment]
我说的是k8s的cluster domain设置，这个和nacos无关，是你需要改变kubernetes dns配置，cluster_domain配置，具体去看kubernetes官网文档

**Comment by paderlol** [comment]
https://blog.csdn.net/newcrane/article/details/78952987 这篇文章有你需要的答案

**Comment by silverlight** [comment]
感谢
